version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=gamestore
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - "./db/data.sql:/docker-entrypoint-initdb.d/data.sql"
